import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#EDF1FA',
    },
    keyboardAvoid: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        justifyContent: 'center',
        paddingHorizontal: 16,
        paddingVertical: 24,
    },
    brandHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 24,
    },
    brandLogo: {
        width: 28,
        height: 28,
        marginRight: 8,
    },
    brandTitle: {
        fontSize: 24,
        fontWeight: '800',
        color: '#004AC6',
        letterSpacing: -0.4,
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 18,
        paddingHorizontal: 22,
        paddingVertical: 26,
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 14,
        elevation: 3,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.7)',
    },
    stepContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 18,
    },
    stepCircle: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    stepActive: {
        backgroundColor: '#004AC6',
    },
    stepActiveText: {
        color: '#FFFFFF',
        fontSize: 12.5,
        fontWeight: '700',
    },
    stepLine: {
        width: 32,
        height: 2,
        backgroundColor: '#D6E4FF',
        marginHorizontal: 8,
    },
    stepInactive: {
        backgroundColor: '#E2E8F0',
    },
    stepInactiveText: {
        color: '#64748B',
        fontSize: 12.5,
        fontWeight: '600',
    },
    title: {
        fontSize: 21,
        fontWeight: '700',
        color: '#111827',
        textAlign: 'center',
        marginBottom: 8,
        letterSpacing: -0.2,
    },
    subtitle: {
        fontSize: 13,
        color: '#6B7280',
        textAlign: 'center',
        lineHeight: 19,
        marginBottom: 20,
        paddingHorizontal: 6,
    },
    errorBox: {
        backgroundColor: '#FEF2F2',
        borderColor: '#FCA5A5',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginBottom: 14,
    },
    errorText: {
        color: '#DC2626',
        fontSize: 12,
        fontWeight: '500',
        textAlign: 'center',
    },
    fieldGroup: {
        marginBottom: 18,
    },
    label: {
        fontSize: 12.5,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 6,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#CBD5E1',
        borderRadius: 8,
        height: 44,
        paddingHorizontal: 12,
    },
    inputIcon: {
        marginRight: 10,
    },
    input: {
        flex: 1,
        fontSize: 13.5,
        color: '#1F2937',
        paddingVertical: 0,
    },
    sendOtpButton: {
        backgroundColor: '#004AC6',
        borderRadius: 8,
        height: 46,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 18,
        shadowColor: '#004AC6',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.22,
        shadowRadius: 6,
        elevation: 2,
    },
    buttonDisabled: {
        opacity: 0.7,
    },
    buttonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    sendOtpButtonText: {
        color: '#FFFFFF',
        fontSize: 14.5,
        fontWeight: '600',
        letterSpacing: 0.2,
    },
    buttonIcon: {
        marginLeft: 6,
    },
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
    },
    backIcon: {
        marginRight: 6,
    },
    backButtonText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#0052CC',
    },
    footerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 22,
    },
    shieldIcon: {
        marginRight: 5,
    },
    footerText: {
        fontSize: 11.5,
        color: '#737686',
        fontWeight: '400',
    },
});