import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#FAF8FF',
    },
    topHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 18,
        paddingVertical: 12,
        backgroundColor: '#FAF8FF',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatarWrapper: {
        width: 38,
        height: 38,
        borderRadius: 19,
        overflow: 'hidden',
        borderWidth: 1.5,
        borderColor: '#D6E4FF',
        marginRight: 10,
    },
    avatarImage: {
        width: '100%',
        height: '100%',
    },
    brandTitle: {
        fontSize: 32,
        fontWeight: '800',
        color: '#004AC6',
        letterSpacing: -0.3,
    },
    bellButton: {
        width: 38,
        height: 38,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 19,
        backgroundColor: '#FFFFFF',
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
        elevation: 1,
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingBottom: 16,
    },
    greetingCard: {
        position: 'relative',
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 18,
        marginVertical: 6,
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 12,
        elevation: 2,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.7)',
        overflow: 'hidden',
    },
    decorativeShape: {
        position: 'absolute',
        top: -20,
        right: -20,
        width: 90,
        height: 90,
        borderRadius: 45,
        backgroundColor: '#EBF2FF',
    },
    greetingDate: {
        fontSize: 12,
        color: '#6B7280',
        fontWeight: '500',
        marginBottom: 4,
    },
    greetingTitle: {
        fontSize: 19,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 6,
        letterSpacing: -0.2,
    },
    empIdRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    empIcon: {
        marginRight: 4,
    },
    empIdText: {
        fontSize: 12,
        color: '#6B7280',
        fontWeight: '500',
    },
    statCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        padding: 14,
        marginVertical: 5,
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
        elevation: 2,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.7)',
    },
    blueStatIconWrapper: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#004AC6',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
    },
    grayStatIconWrapper: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#EDF1FA',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
    },
    statInfo: {
        flex: 1,
    },
    statLabel: {
        fontSize: 10.5,
        fontWeight: '700',
        color: '#64748B',
        letterSpacing: 0.5,
        marginBottom: 2,
    },
    statValue: {
        fontSize: 18,
        fontWeight: '800',
        color: '#111827',
    },
    timelineCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 18,
        marginVertical: 6,
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 12,
        elevation: 2,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.7)',
    },
    timelineTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 14,
    },
    timelineItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    timelineDotIcon: {
        marginRight: 12,
    },
    timelineContent: {
        flex: 1,
    },
    timelineItemTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 3,
    },
    timelineLocationRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    timelineLocationText: {
        fontSize: 12,
        color: '#6B7280',
        marginLeft: 3,
    },
    // Skeleton styles
    skeletonCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 18,
        marginVertical: 6,
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 10,
        elevation: 1,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.7)',
    },
    skeletonBox: {
        backgroundColor: '#E2E8F0',
        borderRadius: 6,
    },
    skeletonCircle: {
        backgroundColor: '#E2E8F0',
        borderRadius: 999,
    },
    skeletonRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    skeletonStatCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        padding: 14,
        marginVertical: 5,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.7)',
    },
    skeletonCheckInCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 18,
        padding: 18,
        marginVertical: 6,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.7)',
    },
});

