import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#EDF1FA',
    },
    keyboardAvoid: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        justifyContent: 'center',
        paddingHorizontal: 16,
        paddingVertical: 24,
    },
    brandHeader: {
        alignItems: 'center',
        marginBottom: 24,
    },
    brandIcon: {
        width: 44,
        height: 48,
        marginBottom: 8,
    },
    brandTitle: {
        fontSize: 24,
        fontWeight: '800',
        color: '#004AC6',
        letterSpacing: -0.4,
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 18,
        paddingHorizontal: 20,
        paddingVertical: 24,
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 14,
        elevation: 3,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.7)',
    },
    title: {
        fontSize: 20,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 4,
        letterSpacing: -0.2,
    },
    subtitle: {
        fontSize: 13,
        color: '#6B7280',
        marginBottom: 18,
    },
    errorBox: {
        backgroundColor: '#FEF2F2',
        borderColor: '#FCA5A5',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginBottom: 14,
    },
    errorText: {
        color: '#DC2626',
        fontSize: 12,
        fontWeight: '500',
    },
    fieldGroup: {
        marginBottom: 14,
    },
    label: {
        fontSize: 12.5,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 6,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F9FAFB',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        height: 44,
        paddingHorizontal: 12,
    },
    inputIcon: {
        marginRight: 10,
    },
    input: {
        flex: 1,
        fontSize: 13.5,
        color: '#1F2937',
        paddingVertical: 0,
    },
    eyeButton: {
        paddingLeft: 8,
        paddingVertical: 4,
    },
    rememberRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 2,
        marginBottom: 18,
    },
    checkboxTouch: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    checkbox: {
        width: 15,
        height: 15,
        borderRadius: 3.5,
        borderWidth: 1.2,
        borderColor: '#CBD5E1',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFFFFF',
        marginRight: 7,
    },
    checkboxChecked: {
        backgroundColor: '#004AC6',
        borderColor: '#004AC6',
    },
    checkmark: {
        color: '#FFFFFF',
        fontSize: 9.5,
        fontWeight: 'bold',
        marginTop: -1,
    },
    rememberText: {
        fontSize: 12.5,
        color: '#4B5563',
    },
    forgotPasswordText: {
        fontSize: 12.5,
        fontWeight: '600',
        color: '#0052CC',
    },
    signInButton: {
        backgroundColor: '#004AC6',
        borderRadius: 8,
        height: 46,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
        shadowColor: '#004AC6',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.22,
        shadowRadius: 6,
        elevation: 2,
    },
    buttonDisabled: {
        opacity: 0.7,
    },
    signInButtonText: {
        color: '#FFFFFF',
        fontSize: 14.5,
        fontWeight: '600',
        letterSpacing: 0.2,
    },
    bottomRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    bottomText: {
        fontSize: 12.5,
        color: '#4B5563',
    },
    contactAdminLink: {
        fontSize: 12.5,
        fontWeight: '600',
        color: '#0052CC',
    },
});