import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#FAF8FF',
    },
    topHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 18,
        paddingVertical: 12,
        backgroundColor: '#FAF8FF',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatarWrapper: {
        width: 38,
        height: 38,
        borderRadius: 19,
        overflow: 'hidden',
        borderWidth: 1.5,
        borderColor: '#D6E4FF',
        marginRight: 10,
    },
    headerAvatarImage: {
        width: '100%',
        height: '100%',
    },
    brandTitle: {
        fontSize: 32,
        fontWeight: '800',
        color: '#004AC6',
        letterSpacing: -0.3,
    },
    bellButton: {
        width: 38,
        height: 38,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 19,
        backgroundColor: '#FFFFFF',
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
        elevation: 1,
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingBottom: 20,
    },
    profileHeroCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 18,
        marginTop: 6,
        marginBottom: 14,
        alignItems: 'center',
        paddingBottom: 20,
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 10,
        elevation: 2,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.7)',
        overflow: 'hidden',
    },
    heroBanner: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 72,
        backgroundColor: '#F4F7FE',
    },
    avatarContainer: {
        marginTop: 26,
        position: 'relative',
        marginBottom: 12,
    },
    largeAvatarWrapper: {
        width: 82,
        height: 82,
        borderRadius: 41,
        borderWidth: 3.5,
        borderColor: '#FFFFFF',
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        elevation: 3,
    },
    largeAvatarImage: {
        width: '100%',
        height: '100%',
    },
    editBadgeButton: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        width: 26,
        height: 26,
        borderRadius: 13,
        backgroundColor: '#004AC6',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#FFFFFF',
    },
    userNameText: {
        fontSize: 20,
        fontWeight: '800',
        color: '#111827',
        marginBottom: 3,
        letterSpacing: -0.2,
    },
    userRoleText: {
        fontSize: 13,
        color: '#6B7280',
        fontWeight: '500',
        marginBottom: 14,
    },
    badgesRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    pillBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 5.5,
        borderRadius: 14,
    },
    badgeIcon: {
        marginRight: 5,
    },
    pillBadgeTextPrimary: {
        fontSize: 12,
        fontWeight: '600',
        color: '#004AC6',
    },
    pillBadgeTextSecondary: {
        fontSize: 12,
        fontWeight: '600',
        color: '#475569',
    },
    sectionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        marginBottom: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
        elevation: 2,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.7)',
    },
    sectionHeader: {
        paddingBottom: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#F1F5F9',
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#111827',
    },
    sectionBody: {
        gap: 14,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    infoIconWrapper: {
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: '#EBF2FF',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    infoTextContainer: {
        flex: 1,
    },
    infoLabel: {
        fontSize: 11,
        color: '#6B7280',
        fontWeight: '500',
        marginBottom: 2,
    },
    infoValue: {
        fontSize: 13.5,
        fontWeight: '600',
        color: '#111827',
    },
    actionButtonsContainer: {
        marginTop: 6,
        marginBottom: 10,
        gap: 10,
    },
    editProfileButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#004AC6',
        borderRadius: 10,
        height: 46,
        shadowColor: '#004AC6',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 2,
    },
    editProfileButtonText: {
        color: '#FFFFFF',
        fontSize: 14.5,
        fontWeight: '600',
    },
    logoutButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        height: 46,
        borderWidth: 1.2,
        borderColor: '#DC2626',
    },
    logoutButtonText: {
        color: '#DC2626',
        fontSize: 14.5,
        fontWeight: '600',
    },
    buttonIcon: {
        marginRight: 7,
    },
});