import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#FAF8FF',
    },
    topHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 18,
        paddingVertical: 12,
        backgroundColor: '#FAF8FF',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatarWrapper: {
        width: 38,
        height: 38,
        borderRadius: 19,
        overflow: 'hidden',
        borderWidth: 1.5,
        borderColor: '#D6E4FF',
        marginRight: 10,
    },
    avatarImage: {
        width: '100%',
        height: '100%',
    },
    brandTitle: {
        fontSize: 32,
        fontWeight: '800',
        color: '#004AC6',
        letterSpacing: -0.3,
    },
    bellButton: {
        width: 38,
        height: 38,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 19,
        backgroundColor: '#FFFFFF',
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
        elevation: 1,
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingBottom: 24,
    },
    titleSection: {
        marginTop: 8,
        marginBottom: 16,
    },
    screenTitle: {
        fontSize: 22,
        fontWeight: '800',
        color: '#111827',
        marginBottom: 4,
        letterSpacing: -0.2,
    },
    screenSubtitle: {
        fontSize: 13,
        color: '#6B7280',
    },
    sectionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        marginVertical: 7,
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
        elevation: 2,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.7)',
        overflow: 'hidden',
    },
    sectionHeader: {
        backgroundColor: '#F3F6FD',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(226, 232, 240, 0.6)',
    },
    sectionHeaderText: {
        fontSize: 12.5,
        fontWeight: '600',
        color: '#374151',
    },
    sectionBody: {
        paddingHorizontal: 16,
        paddingVertical: 4,
    },
    settingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
    },
    clickableRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 13,
    },
    rowLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    rowIcon: {
        marginRight: 12,
    },
    rowTitle: {
        fontSize: 13.5,
        fontWeight: '500',
        color: '#111827',
    },
    rowSubtitle: {
        fontSize: 11.5,
        color: '#6B7280',
        marginTop: 2,
    },
    signOutTitle: {
        fontSize: 13.5,
        fontWeight: '600',
        color: '#DC2626',
    },
    rowDivider: {
        height: 1,
        backgroundColor: '#F1F5F9',
    },
    footerSection: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 24,
        marginBottom: 8,
    },
    footerLinksRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    footerLinkText: {
        fontSize: 11.5,
        color: '#6B7280',
        fontWeight: '400',
    },
    footerDot: {
        width: 3.5,
        height: 3.5,
        borderRadius: 2,
        backgroundColor: '#9CA3AF',
        marginHorizontal: 10,
    },
    versionText: {
        fontSize: 11,
        color: '#9CA3AF',
    },
});