import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#EDF1FA',
    },
    keyboardAvoid: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        justifyContent: 'center',
        paddingHorizontal: 16,
        paddingVertical: 24,
    },
    brandHeader: {
        alignItems: 'center',
        marginBottom: 24,
    },
    brandIcon: {
        width: 44,
        height: 48,
        marginBottom: 8,
    },
    brandTitle: {
        fontSize: 24,
        fontWeight: '800',
        color: '#004AC6',
        letterSpacing: -0.4,
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 18,
        paddingHorizontal: 22,
        paddingVertical: 26,
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 14,
        elevation: 3,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.7)',
    },
    title: {
        fontSize: 21,
        fontWeight: '700',
        color: '#111827',
        textAlign: 'center',
        marginBottom: 8,
        letterSpacing: -0.2,
    },
    subtitle: {
        fontSize: 13,
        color: '#6B7280',
        textAlign: 'center',
        lineHeight: 18,
        marginBottom: 20,
        paddingHorizontal: 6,
    },
    errorBox: {
        backgroundColor: '#FEF2F2',
        borderColor: '#FCA5A5',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginBottom: 14,
    },
    errorText: {
        color: '#DC2626',
        fontSize: 12,
        fontWeight: '500',
        textAlign: 'center',
    },
    fieldGroup: {
        marginBottom: 14,
    },
    label: {
        fontSize: 12.5,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 6,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#CBD5E1',
        borderRadius: 8,
        height: 44,
        paddingHorizontal: 12,
    },
    input: {
        flex: 1,
        fontSize: 13.5,
        color: '#1F2937',
        paddingVertical: 0,
    },
    eyeButton: {
        paddingLeft: 8,
        paddingVertical: 4,
    },
    strengthContainer: {
        marginTop: -4,
        marginBottom: 16,
    },
    strengthHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 6,
    },
    strengthLabel: {
        fontSize: 11.5,
        color: '#4B5563',
        fontWeight: '500',
    },
    strengthValue: {
        fontSize: 11.5,
        fontWeight: '600',
    },
    barsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 6,
    },
    barSegment: {
        flex: 1,
        height: 4,
        borderRadius: 2,
        backgroundColor: '#E2E8F0',
        marginHorizontal: 2.5,
    },
    strengthHint: {
        fontSize: 11,
        color: '#6B7280',
        marginTop: 2,
    },
    resetButton: {
        backgroundColor: '#004AC6',
        borderRadius: 8,
        height: 46,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 6,
        marginBottom: 18,
        shadowColor: '#004AC6',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.22,
        shadowRadius: 6,
        elevation: 2,
    },
    buttonDisabled: {
        opacity: 0.7,
    },
    buttonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    resetButtonText: {
        color: '#FFFFFF',
        fontSize: 14.5,
        fontWeight: '600',
        letterSpacing: 0.2,
    },
    buttonIcon: {
        marginLeft: 6,
    },
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
    },
    backIcon: {
        marginRight: 6,
    },
    backButtonText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#0052CC',
    },
    footerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 22,
    },
    footerLink: {
        fontSize: 11.5,
        color: '#6B7280',
        fontWeight: '400',
    },
    footerDot: {
        width: 3.5,
        height: 3.5,
        borderRadius: 2,
        backgroundColor: '#9CA3AF',
        marginHorizontal: 12,
    },
});
