import { StyleSheet } from "react-native";

export
    const styles = StyleSheet.create({
        safeArea: {
            flex: 1,
            backgroundColor: '#EDF1FA',
        },
        keyboardAvoid: {
            flex: 1,
        },
        scrollContent: {
            flexGrow: 1,
            justifyContent: 'center',
            paddingHorizontal: 16,
            paddingVertical: 24,
        },
        card: {
            backgroundColor: '#FFFFFF',
            borderRadius: 18,
            paddingHorizontal: 20,
            paddingVertical: 28,
            shadowColor: '#1A2A4E',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.05,
            shadowRadius: 14,
            elevation: 3,
            borderWidth: 1,
            borderColor: 'rgba(226, 232, 240, 0.7)',
            alignItems: 'center',
        },
        iconContainer: {
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: 16,
        },
        emailBadgeImage: {
            width: 58,
            height: 58,
        },
        title: {
            fontSize: 21,
            fontWeight: '700',
            color: '#111827',
            textAlign: 'center',
            marginBottom: 6,
            letterSpacing: -0.2,
        },
        subtitle: {
            fontSize: 13,
            color: '#6B7280',
            textAlign: 'center',
            lineHeight: 18,
            marginBottom: 22,
            paddingHorizontal: 12,
        },
        errorBox: {
            backgroundColor: '#FEF2F2',
            borderColor: '#FCA5A5',
            borderWidth: 1,
            borderRadius: 8,
            paddingHorizontal: 12,
            paddingVertical: 8,
            marginBottom: 16,
            width: '100%',
        },
        errorText: {
            color: '#DC2626',
            fontSize: 12,
            fontWeight: '500',
            textAlign: 'center',
        },
        otpRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            width: '100%',
            marginBottom: 24,
            paddingHorizontal: 2,
        },
        otpBox: {
            width: 44,
            height: 50,
            borderRadius: 8,
            borderWidth: 1.2,
            borderColor: '#CBD5E1',
            backgroundColor: '#FFFFFF',
            fontSize: 20,
            fontWeight: '700',
            color: '#111827',
            textAlign: 'center',
            paddingVertical: 0,
        },
        otpBoxFocused: {
            borderColor: '#004AC6',
            borderWidth: 1.6,
        },
        otpBoxFilled: {
            borderColor: '#004AC6',
            backgroundColor: '#FFFFFF',
        },
        verifyButton: {
            backgroundColor: '#004AC6',
            borderRadius: 8,
            height: 46,
            width: '100%',
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: 20,
            shadowColor: '#004AC6',
            shadowOffset: { width: 0, height: 3 },
            shadowOpacity: 0.22,
            shadowRadius: 6,
            elevation: 2,
        },
        buttonDisabled: {
            opacity: 0.7,
        },
        buttonContent: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
        },
        verifyButtonText: {
            color: '#FFFFFF',
            fontSize: 14.5,
            fontWeight: '600',
            letterSpacing: 0.2,
        },
        buttonIcon: {
            marginLeft: 6,
        },
        resendContainer: {
            alignItems: 'center',
            justifyContent: 'center',
        },
        resendPrompt: {
            fontSize: 12.5,
            color: '#4B5563',
            marginBottom: 4,
        },
        timerText: {
            fontSize: 12.5,
            color: '#6B7280',
        },
        resendLinkDisabled: {
            color: '#93C5FD',
            fontWeight: '600',
        },
        resendLinkActive: {
            color: '#0052CC',
            fontWeight: '600',
            fontSize: 12.5,
        },
    });