import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#EDF1FA',
    },
    keyboardAvoid: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        justifyContent: 'center',
        paddingHorizontal: 16,
        paddingVertical: 24,
    },
    brandHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 6,
    },
    brandLogo: {
        width: 28,
        height: 28,
        marginRight: 8,
    },
    brandTitle: {
        fontSize: 24,
        fontWeight: '800',
        color: '#004AC6',
        letterSpacing: -0.4,
    },
    subtitle: {
        fontSize: 13,
        color: '#6B7280',
        textAlign: 'center',
        marginBottom: 20,
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 18,
        paddingHorizontal: 20,
        paddingVertical: 24,
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 14,
        elevation: 3,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.7)',
    },
    errorBox: {
        backgroundColor: '#FEF2F2',
        borderColor: '#FCA5A5',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginBottom: 14,
    },
    errorText: {
        color: '#DC2626',
        fontSize: 12,
        fontWeight: '500',
    },
    fieldGroup: {
        marginBottom: 13,
    },
    label: {
        fontSize: 12.5,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 6,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F3F6FD',
        borderWidth: 1,
        borderColor: '#D8E2F0',
        borderRadius: 8,
        height: 44,
        paddingHorizontal: 12,
    },
    inputIcon: {
        marginRight: 10,
    },
    input: {
        flex: 1,
        fontSize: 13.5,
        color: '#1F2937',
        paddingVertical: 0,
    },
    eyeButton: {
        paddingLeft: 8,
        paddingVertical: 4,
    },
    termsRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginTop: 4,
        marginBottom: 18,
        paddingRight: 12,
    },
    checkboxTouch: {
        marginRight: 8,
        marginTop: 2,
    },
    checkbox: {
        width: 16,
        height: 16,
        borderRadius: 3.5,
        borderWidth: 1.2,
        borderColor: '#CBD5E1',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFFFFF',
    },
    checkboxChecked: {
        backgroundColor: '#004AC6',
        borderColor: '#004AC6',
    },
    termsText: {
        flex: 1,
        fontSize: 11.5,
        color: '#4B5563',
        lineHeight: 17,
    },
    termsLink: {
        color: '#0052CC',
        fontWeight: '600',
    },
    createAccountButton: {
        backgroundColor: '#004AC6',
        borderRadius: 8,
        height: 46,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 18,
        shadowColor: '#004AC6',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.22,
        shadowRadius: 6,
        elevation: 2,
    },
    buttonDisabled: {
        opacity: 0.7,
    },
    buttonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    createAccountButtonText: {
        color: '#FFFFFF',
        fontSize: 14.5,
        fontWeight: '600',
        letterSpacing: 0.2,
    },
    buttonIcon: {
        marginLeft: 6,
    },
    bottomRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    bottomText: {
        fontSize: 12.5,
        color: '#4B5563',
    },
    signInLink: {
        fontSize: 12.5,
        fontWeight: '600',
        color: '#0052CC',
    },
    // Success Screen Styles
    successContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    successCard: {
        width: '100%',
        alignItems: 'center',
        paddingHorizontal: 8,
    },
    successIconOuter: {
        width: 110,
        height: 110,
        borderRadius: 55,
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.08,
        shadowRadius: 16,
        elevation: 4,
        marginBottom: 24,
    },
    successIconInner: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#004AC6',
        alignItems: 'center',
        justifyContent: 'center',
    },
    successTitle: {
        fontSize: 24,
        fontWeight: '800',
        color: '#111827',
        textAlign: 'center',
        marginBottom: 10,
        letterSpacing: -0.3,
    },
    successSubtitle: {
        fontSize: 13.5,
        color: '#6B7280',
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: 32,
        paddingHorizontal: 12,
    },
    continueButton: {
        backgroundColor: '#004AC6',
        borderRadius: 8,
        height: 48,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
        shadowColor: '#004AC6',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.22,
        shadowRadius: 6,
        elevation: 2,
    },
    continueButtonText: {
        color: '#FFFFFF',
        fontSize: 15,
        fontWeight: '600',
    },
    dashboardButton: {
        backgroundColor: '#F3F6FD',
        borderWidth: 1,
        borderColor: '#D8E2F0',
        borderRadius: 8,
        height: 48,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    dashboardButtonText: {
        color: '#1F2937',
        fontSize: 15,
        fontWeight: '600',
    },
});