import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#FAF8FF',
    },
    topBar: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#FAF8FF',
    },
    backButton: {
        paddingRight: 10,
        paddingVertical: 4,
    },
    topBarTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: '#004AC6',
        letterSpacing: -0.2,
    },
    keyboardAvoid: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingTop: 8,
        paddingBottom: 24,
    },
    mainCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 18,
        paddingHorizontal: 18,
        paddingVertical: 22,
        shadowColor: '#1A2A4E',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 12,
        elevation: 2,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.7)',
    },
    photoContainer: {
        alignSelf: 'center',
        position: 'relative',
        marginBottom: 6,
    },
    avatarWrapper: {
        width: 92,
        height: 92,
        borderRadius: 46,
        borderWidth: 3,
        borderColor: '#FFFFFF',
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 6,
        elevation: 2,
    },
    avatarImage: {
        width: '100%',
        height: '100%',
    },
    cameraBadgeButton: {
        position: 'absolute',
        bottom: 1,
        right: 1,
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#004AC6',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#FFFFFF',
    },
    changePhotoBtn: {
        alignSelf: 'center',
        marginBottom: 20,
    },
    changePhotoText: {
        fontSize: 12.5,
        fontWeight: '700',
        color: '#004AC6',
    },
    errorBox: {
        backgroundColor: '#FEF2F2',
        borderColor: '#FCA5A5',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginBottom: 14,
    },
    errorText: {
        color: '#DC2626',
        fontSize: 12,
        fontWeight: '500',
        textAlign: 'center',
    },
    fieldGroup: {
        marginBottom: 15,
    },
    fieldLabel: {
        fontSize: 12.5,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 6,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8FAFC',
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 8,
        height: 44,
        paddingHorizontal: 12,
    },
    inputDisabled: {
        backgroundColor: '#F1F5F9',
        borderColor: '#E2E8F0',
    },
    inputIcon: {
        marginRight: 10,
    },
    input: {
        flex: 1,
        fontSize: 13.5,
        color: '#1F2937',
        paddingVertical: 0,
    },
    disabledText: {
        flex: 1,
        fontSize: 13.5,
        color: '#64748B',
    },
    helperText: {
        fontSize: 11,
        color: '#6B7280',
        marginTop: 4,
        marginLeft: 2,
    },
    infoHelperRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
        marginLeft: 2,
    },
    infoIcon: {
        marginRight: 4,
    },
    helperTextNoMargin: {
        fontSize: 11,
        color: '#6B7280',
    },
    actionButtonsContainer: {
        marginTop: 10,
        gap: 10,
    },
    saveButton: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#004AC6',
        borderRadius: 10,
        height: 46,
        shadowColor: '#004AC6',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 2,
    },
    buttonDisabled: {
        opacity: 0.7,
    },
    saveButtonText: {
        color: '#FFFFFF',
        fontSize: 14.5,
        fontWeight: '600',
    },
    cancelButton: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        height: 46,
        borderWidth: 1,
        borderColor: '#CBD5E1',
    },
    cancelButtonText: {
        color: '#374151',
        fontSize: 14.5,
        fontWeight: '600',
    },
});